services:
  - type: web
    name: gmrit-results
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.9
